namespace: robsonmantovani
name: elasticsearch_security
version: 1.0.1
readme: README.md
description: Collection for managing Elasticsearch security.
license: BSD-2-Clause
authors:
  - Robson Mantovani <robsonmantovani@gmail.com>
repository: https://github.com/robsonmantovani/ansible_elasticsearch_security

