- name: Create or Invalidate Elasticsearch Security API Key
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Manage Elasticsearch Security API Key
      elasticsearch_security_api-key:
        state: present
        es_url: http://localhost:9200
        es_user: admin
        es_pass: password
        user_name: user1
        api_key_name: my_api_key
        api_key_role_descriptors:
          my_role: {}

